version: "3.8"

# docker-compose -f docker-compose-dev.yml up -d --build
services:
  api-dev:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    container_name: ac2-api-dev
    ports:
      - 9000:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: always
    