version: "3.8"

# docker-compose -f docker-compose-staging.yml up -d --build
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    container_name: ac2-api-staging
    ports:
      - 6000:8080
    volumes:
      - ./:/app
    environment:
      - SPRING_PROFILES_ACTIVE=staging