version: "3.8"

# docker-compose -f docker-compose-staging.yml up -d --build
services:
  api-staging:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    container_name: ac2-api-staging
    ports:
      - 6001:8080
    environment:
      - SPRING_PROFILES_ACTIVE=staging